project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('project.userlogin.urls')),
    url(r'^todo/', include('project.todo.urls')),
]

project/userlogin/urls.py
from django.conf.urls import include, url
from .views import LogoutView, LoginView, ProfileView, RegisterView
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^auth/login/$', LoginView.as_view(), name='id.views.auth'),
    url(r'^auth/logout/$', LogoutView.as_view(), name='id.views.logout'),
    url(r'^auth/profile/$', login_required(ProfileView.as_view()), name='id.views.profile'),
    url(r'^auth/register/$', RegisterView.as_view(), name='id.views.register'),
   	url(r'^$', RedirectView.as_view(pattern_name='id.views.auth', permanent=False)),
]

project/todo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from django.contrib.auth.models import User


class Todo(models.Model):
    """
    TODO Model
    Allows to create notes for an specific user if public
    """
    title   = models.CharField(_('Título'), max_length=255)
    content = models.TextField(_('Contenido'), blank=True)
    private = models.BooleanField(_('Nota privada'), default=False)
    user    = models.ForeignKey(User)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

project/userlogin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

project/userlogin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import pgettext_lazy, ugettext_lazy as _


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UserProfileForm(UserChangeForm):
    fakename = forms.CharField(label=_("Nombre de usuario"),max_length=30,
     required=False, help_text='', disabled=True)
    first_name = forms.CharField(max_length=30, label=("Nombre"),
        required=False, help_text='')
    last_name = forms.CharField(max_length=30, label=("Apellido"),
     required=False, help_text='')
    email = forms.EmailField(max_length=254, help_text='',required=False)
    password1 = forms.CharField(label=_("Contrasena"),required=False,
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Confirmar Contrasena"),required=False,
        widget=forms.PasswordInput,
        help_text=_(""))
    password = None

    class Meta:
        model = User
        fields = ('fakename', 'first_name', 'last_name', 'email')
    

project/userlogin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import logout
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, TemplateView
from .forms import SignUpForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password

class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    template_name = "userlogin/login.html"
    success_url = '/todo/home/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/auth/login/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

class ProfileView(FormView):
    template_name = "userlogin/profile.html"
    success_url = '/auth/profile/'
    form_class = UserProfileForm
    redirect_field_name = REDIRECT_FIELD_NAME


    def form_valid(self, form):
        user = self.request.user

        first_name = form.cleaned_data.get('first_name')
        if first_name:
            user.first_name = first_name
        last_name = form.cleaned_data.get('last_name')
        if last_name:
            user.last_name = last_name
        email = form.cleaned_data.get('email')
        if email:
            user.email = email
        password1 = form.cleaned_data.get('password1')
        password2 = form.cleaned_data.get('password2')
        if len(password1) > 0:
            if password1 == password2:
                user.password = make_password(password1)
                user.save()
                logout(self.request)

        
        user.save()
        return super(ProfileView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

    def get_initial(self):
        initial = super(ProfileView, self).get_initial()
        initial['fakename'] = self.request.user.username
        initial['first_name'] = self.request.user.first_name
        initial['email'] = self.request.user.email
        initial['last_name'] = self.request.user.last_name
        return initial

class RegisterView(FormView):
    template_name = "userlogin/register.html"
    success_url = '/todo/home/'
    form_class = SignUpForm
    redirect_field_name = REDIRECT_FIELD_NAME
    
    def form_valid(self, form):
        form.save(commit = True)
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

project/userlogin/templates/userlogin/base.html
{# HTML5 declaration #}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Home {% endblock title %} | Todo App</title>
        {% block head_favicon %}
            <link rel="icon" type="image/png"
                  href="{{ STATIC_URL }}images/favicon.ico">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {# Load the tag library #}
    {% load bootstrap3 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

project/userlogin/templates/userlogin/login.html
{% extends 'userlogin/base.html' %}
{% block title %}
Please log in
{% endblock %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'id.views.auth' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_title">Iniciar Sesión</label></td>
                        <td><label for="id_title"><a href="{% url 'id.views.register' %}">Registro</a></label></td>
                    </tr>
                    <tr>
                        <td><label for="id_username">Usuario</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Contraseña</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Iniciar Sesión" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

project/userlogin/templates/userlogin/profile.html
{% extends "todo/base.html" %}
{% block title %}
Update Profile
{% endblock %}

{% block subtitle %}Actualizar Perfil{% endblock %}
{% block content %}

<form method="post" action = "{% url 'id.views.profile' %}" novalidate>
  {% csrf_token %}
  <table>
    {{ form.as_table}}
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock content %}

project/userlogin/templates/userlogin/register.html
{% extends 'userlogin/base.html' %}
{% block title %}
Please register
{% endblock %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'id.views.register' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_title"><a href="{% url 'id.views.auth' %}">Iniciar Sesión</a></label></label></td>
                        <td><label for="id_title">Registro</td>
                    </tr>
                    <tr>
                        <td><label for="id_username">Nombre de Usuario</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control" value=""></td>
                    </tr>
                    <tr>
                        <td><label for="id_email">Email</label></td>
                        <td><input id="id_email" name="email" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_name">Nombre</label></td>
                        <td><input id="id_name" name="first_name" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_lastname">Apellido</label></td>
                        <td><input id="id_lastname" name="last_name" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Contraseña</label></td>
                        <td><input id="id_password" name="password1" 
                                   type="password" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_confirm_password">Confirmar Contraseña</label></td>
                        <td><input id="id_confirm_password" name="password2" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    Please correct the error{{ f.errors|pluralize }} below.
                        {{ form.errors }}
                {% endif %}

                <input type="submit" value="Registrar" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}